apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
  name: system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
  labels:
    control-plane: controller-manager
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        control-plane: controller-manager
    spec:
      securityContext:
        runAsNonRoot: false
      containers:
      - command:
        - /controller/manager
        args:
        - --leader-elect
        image: controller:latest
        name: manager
        imagePullPolicy: IfNotPresent
        securityContext:
          allowPrivilegeEscalation: false
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        # TODO(user): Configure the resources accordingly based on the project requirements.
        # More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
        volumeMounts:
          - name: timezone-volume
            mountPath: /etc/localtime
            readOnly: true
          - name: kube-config
            mountPath: /pkg/kube-config/config
            subPath: config
      volumes:
        - name: timezone-volume
          hostPath:
            path: /etc/localtime
        - configMap:
            name: kube-config
          name: kube-config
      serviceAccountName: controller-manager
      terminationGracePeriodSeconds: 10
      hostNetwork: true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-config
data:
  config: |- 
    apiVersion: v1
    clusters:
      - cluster:
          certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM1ekNDQWMrZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJME1ETXhNekV4TXpNeU1sb1hEVE0wTURNeE1URXhNek15TWxvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTGRsCklmZXhtd1FvT3lNZlVtd3lwcXJJaHRQalZyRHdFcU9OMzl2cnNzSFBJSUlhRlNvZFAvWThaTHRvdkJQeXZORnUKc0dNSDNXK0hFekdaUnFXcWhLZGpQL1F2SlRncXRnYmQxQkpndS96Rzl3ajJwanJlVWppTGZ2WTZodzA0SFFIZQppVUZyN2tEdUVXa3RXYU9JYWhYMkgvMDlsMXU1MVpYaEF1VGJoUUF0TmlLQTRtTHFlOGs2SzZjNGF5bVBjdlNGCkZxeDZwN1NRS0xvMXFncWkvQXZrdW9TeUNuY2puczJyYk9HWXM2OWdUT05ncFhxVmxlQnpDRXlVci9ucGVyUUwKUEIyU1UreERLMkRVWTZrQ2RsWVBOZjAzc1ErWXFRTFdjalA3eXY1N3RnZUxqU1A3aUJHRWFJbzU3cDhWYldBeApsaGxsL1dwQXN6aHgxLzJEY0hjQ0F3RUFBYU5DTUVBd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZNZFk3VHFYdnlFZGZZNmhNcUtNbVVObGpKeGZNQTBHQ1NxR1NJYjMKRFFFQkN3VUFBNElCQVFDSzlGN00xQzVMbVpYYzFMUlcyVWFkOTdQeFpNS09lQjlSQnVGVjlFSXZXVmJva0ovcgozVzkyMURZYWFVUU0xaVZmQURUU3ZtcFdWZlU1QXBWVGt5NDZNOUlJZDZYMWNPNmZ6eFJSRkErNmwrLzhpTTA0CnVlckhwVkRDV3p0V2Q2ekJoTkUxdExhUmcxOWFud0RQWGdPNFdqbENZd3VtdGVBK0hEcEUyN0l4QlMxS2JXeG4KUm5VNGFNYkJYTTI3Q3lUWnA4blFwb1Fkbm44Z3lOYmtNZ3NmQWR2eWxISFhrMTRyY25WMG1TQ3N6djJ2RTd5cQovQjI1S1ZOdG43WDhpZDJGQThzcEI4cEh3NTE3Sk9RQUs5amQ5Y2s1dXhGUXJGa0xVaTVhU2o1amE5VStMWVVJCngweEJKTUpiL04vd0tTYlkxT01EK0Z0ODMzRHh0bEQzL1dULwotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
          server: https://192.168.28.130:6443
        name: kubernetes
    contexts:
      - context:
          cluster: kubernetes
          user: kubernetes-admin
        name: kubernetes-admin@kubernetes
    current-context: kubernetes-admin@kubernetes
    kind: Config
    preferences: {}
    users:
      - name: kubernetes-admin
        user:
          client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURJVENDQWdtZ0F3SUJBZ0lJRFE5MWV3TDlDRzB3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TkRBek1UTXhNVE16TWpKYUZ3MHlOVEF6TVRNeE1UTXpNak5hTURReApGekFWQmdOVkJBb1REbk41YzNSbGJUcHRZWE4wWlhKek1Sa3dGd1lEVlFRREV4QnJkV0psY201bGRHVnpMV0ZrCmJXbHVNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQXNGcFY2TUhCUW1NSGlFQnYKd0N4NDlBbVM1bGR1Q0NWWFlwVk5xd1F5ajZsbHRrS0UwbDFLYzBnVStNbEU0c0E1blNrVjJOS3lKcmlWZW9qeApEaFFVb25xMS9Va3Z3Tk9YU3dvQ1RrYUNZelN4TjRXeXV4U0FGNDNzd0FQOWZSdmRuSG8zdG1ReEU5eURzU1FGCkdNN3lVM0g4U1ZDWnlqZzNUQnNtU0NHa3Iydyt5R005UHIvLzBWOWtIRnBienFGK0VFekh0YVNtUzhabUFKZGQKZXI3ZE9jM1NWVVF3YVBFZFkweUhvRDBnZ2ZrRENiTG4xNm55NWdFR0JmN0RoNmxkOFRKaHpiSVQ0UkhiRG9CUQozemh1TVV6aXA3NkVhcjc5UW12Wm1yL0UzWUJ0cVRWU3lHRjFKZFVBWlJwOHFTNEYwNU9Hb0dqYS9qMWVXelpzCnRjNWt1d0lEQVFBQm8xWXdWREFPQmdOVkhROEJBZjhFQkFNQ0JhQXdFd1lEVlIwbEJBd3dDZ1lJS3dZQkJRVUgKQXdJd0RBWURWUjBUQVFIL0JBSXdBREFmQmdOVkhTTUVHREFXZ0JUSFdPMDZsNzhoSFgyT29US2lqSmxEWll5YwpYekFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBYkI0Z2NURC9zS1hMNzlCWUgralNmdWoyTHRlM2VCUWFXbGJrCks0RjVrWHpYU3QzSnNmUmxRRlNmUUpaY3FwUmdnMFcyQkdicXc0MGtSMmNmbUZLeVR0TTU4T2ZrZEdyVUpabE8KWkM5NEUwT2FNS0l1czd0TnJKWHQ2ZSt1Y3N1WXBOTmlBbndERDNxeUJhYjdYY1dlUGNBTDRPUXc2Z1lLcjNIZQpRbnBaS1o0SXBYUnlETFp4OHZoZmFVb01kdlQvRFR6ejh4VUQxRGYzSlFQNFhZa3VvUUwxaDA4aTZtZS9hWWFOCkE3MW9FQzFFSndrOHFPSXAyS1dWUGRHekI4TndNSkFWNmRBcytQZ1M0TW9mTUNPVW1La2tHWXRDQUpXb3kxRk0KOGFQVjNFK0VqYXNvNXY5Q0Fpdng5ZFAxVUN1T1RuVHpuRTUyTFJrUWU4Q1kxM3lzTWc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
          client-key-data: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb3dJQkFBS0NBUUVBc0ZwVjZNSEJRbU1IaUVCdndDeDQ5QW1TNWxkdUNDVlhZcFZOcXdReWo2bGx0a0tFCjBsMUtjMGdVK01sRTRzQTVuU2tWMk5LeUpyaVZlb2p4RGhRVW9ucTEvVWt2d05PWFN3b0NUa2FDWXpTeE40V3kKdXhTQUY0M3N3QVA5ZlJ2ZG5IbzN0bVF4RTl5RHNTUUZHTTd5VTNIOFNWQ1p5amczVEJzbVNDR2tyMncreUdNOQpQci8vMFY5a0hGcGJ6cUYrRUV6SHRhU21TOFptQUpkZGVyN2RPYzNTVlVRd2FQRWRZMHlIb0QwZ2dma0RDYkxuCjE2bnk1Z0VHQmY3RGg2bGQ4VEpoemJJVDRSSGJEb0JRM3podU1VemlwNzZFYXI3OVFtdlptci9FM1lCdHFUVlMKeUdGMUpkVUFaUnA4cVM0RjA1T0dvR2phL2oxZVd6WnN0YzVrdXdJREFRQUJBb0lCQUQ0ZEkwTWU4MTNabVc2UgpHNHM1WHNTOWxvTVE2azF1TVpBa2ZEMnU5Y3dKNHl4RjA1aHdpV2QvVFB1dmtGYTVVOUdhQmZyZmd5WUdQNGZ3Ck1jOCtuV0g1REo2UXA0UW9RcEtJalBWYStsUE0zRnBzK2QzUXc2a0lNUW9VbmJUeUdxVWhtdnZmNERWWnB2eSsKYmhrbDBzNDNTSi9lQnJ6bC9md05WL2R4K2hwYTFNY2E4NW4zTC9wSXNyYnZLZFVLNm1IUkhGYkJUUkZ3bFAvVApySmgzdlFRSFJ4YlB3Sk0zSmUxSHRHRmd5TUNBeWl4bUxzSUUyRE5XQWp5L0pCNnBFc29neVBGU1dzdVpjN3hmCm5QdmhheGRLNlRNR2Vka2pQTEU5MHhEUjUxbWJhN3F2S1NVNWNTaDhxZGlCM3lEYTlOckpUWUc2TXRuVGpJaFQKVlpoeGJpRUNnWUVBeExieGpNUlJDS1MxRVVkUFhnbTNma3BmUy85MG9kZkx2aEdsc2xDbDg1Q2w0bTg2c3VaMQpwak9VeG9uRXBKZU4rc1VBQUNZWEFZYndjMkhEc1VaeTVCMkRjbXJIakQ5b2VodEIxTmE1bTJ3ejhiODlrb0hrClF0d3JjRGZKMHNTSStnRy9qTklUK3luM1U1d1lobWVuL3BySXAyQTROaHZpb3UyTjE0UnJIK3NDZ1lFQTVZQnQKeWU2Q0VGZ3dEVUZKWms0ZHlXQ3RoZXFWS2ZhMHFOYVgxT0tQZVpoQVB2amtmUVdtMDllUWJuRHNGczBjZUsyKwpTRFlXTHpMS0crdmU0TkRkWWJFaFhYMm0zYXZpWGw0MzVKRGhmcnJmUGthUXFWYVUvbFYvMVphcytBbE1ZN2RQCk9aTk5tQ0Rka2tuTncyNStoZkdaOHZKdFpCVW51UzJyRnhCcWFuRUNnWUFmS0FxaURRWDRwSDI1T3Q0ck9zYkIKVGU1Q0R6ZmQybHYrd3JUSHhWWkRlWW1NajZsd1pHZ0Y1dTJOZEl5Y3RSUmJ2NC84ZGd2MnhmU1hrY2g0NzN1SwovZEd2OFpHaGVQbUhQWUh6di82dHl6bCs5SmMvK1NxNkhEMFZEUUQrVFBxVS9tbmtWL0dxT2o5ZUVyOGZxcE5GCkZDYnJ1NldyakVjZEh4cjBJNWtEK1FLQmdRQ2Nna0hjNU1kVUNCLzAyaUlKSDVxV20xU2FyOGc3anQvVENFMFEKdzlTZVVxTDFqdHliR2dDVUZUeU01SHRNYldKT05nWSt6b3ZBY2oxOFh4Vm1jV21YMXFqdlRlSSs1NW4vU3ZlSQo2dmlzYVJvWEtSNDhMU3g4YWFnODYzMVh4VmVQNVJHbExQeE1rNVVtenlnQWI5amUxVTFzYmNFRjhKdGZZSEo5Cnp4Y1RNUUtCZ0NaS01qK2pybU5Wd0dWNzhWTHZTNXVUV2NDMjF4cVl2UnJ6TERLZytlR2pTNjJzeGhCUEVTSUMKSHlNWXBiOVFIRkJiWERqRmREaVlRakVUMWJ1L2JyNU1VNkszclUzZW1YUTFsS01vQy9KVDR1aFNJbVlQTlY4NApGMlk2STh4di9BZmF3SmkvNG9Rcy9xdytWZk9zbVlPZnZ2Z2hraGFDQU5CR1kzdTF2QjlSCi0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==
