# permissions for end users to view nodedeploys.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nodedeploy-viewer-role
rules:
- apiGroups:
  - node.nodedeploy
  resources:
  - nodedeploys
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - node.nodedeploy
  resources:
  - nodedeploys/status
  verbs:
  - get
