---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: node-deploy-cluster-role-binding
  namespace: "{{ .Release.Namespace }}"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: node-deploy-cluster-role
subjects:
  - kind: ServiceAccount
    name: {{ include "node-deploy.serviceAccountName" . }}
    namespace: "{{ .Release.Namespace }}"

