apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: node-deploy-cluster-role
  namespace: "{{ .Release.Namespace }}"
rules:
  - apiGroups:
      - ""
    resources:
      - events
    verbs: ["get", "create", "patch"]
  - apiGroups:
      - ""
    resources:
      - nodes
      - pods
      - DaemonSets
    verbs:
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
  - apiGroups:
      - node.nodedeploy
    resources:
      - nodedeploys
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - node.nodedeploy
    resources:
      - nodedeploys/finalizers
    verbs:
      - update
  - apiGroups:
      - node.nodedeploy
    resources:
      - nodedeploys/status
    verbs:
      - get
      - patch
      - update
